/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jademula_DirectInput */

#ifndef _Included_jademula_DirectInput
#define _Included_jademula_DirectInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jademula_DirectInput
 * Method:    init
 * Signature: (Ljava/awt/Window;)Z
 */
JNIEXPORT jboolean JNICALL Java_jademula_DirectInput_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jademula_DirectInput
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jademula_DirectInput_close
  (JNIEnv *, jobject);

/*
 * Class:     jademula_DirectInput
 * Method:    poll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jademula_DirectInput_poll
  (JNIEnv *, jobject);

/*
 * Class:     jademula_DirectInput
 * Method:    joyAxes
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jademula_DirectInput_joyAxes
  (JNIEnv *, jobject, jint);

/*
 * Class:     jademula_DirectInput
 * Method:    joyButtons
 * Signature: (I)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_jademula_DirectInput_joyButtons
  (JNIEnv *, jobject, jint);

/*
 * Class:     jademula_DirectInput
 * Method:    getJoyNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jademula_DirectInput_getJoyNum
  (JNIEnv *, jobject);

/*
 * Class:     jademula_DirectInput
 * Method:    getKeys
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_jademula_DirectInput_getKeys
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
